MODEL:
  WEIGHTS: "detectron2://TridentNet/tridentnet_fast_R_50_C4_1x/148572687/model_final_756cda.pkl"
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_trident_resnet_backbone"
  ROI_HEADS:
    NAME: "TridentRes5ROIHeads"
    POSITIVE_FRACTION: 0.5
    BATCH_SIZE_PER_IMAGE: 128
    PROPOSAL_APPEND_GT: False
    NUM_CLASSES: 10
  PROPOSAL_GENERATOR:
    NAME: "TridentRPN"
  RPN:
    PRE_NMS_TOPK_TRAIN: 500
    PRE_NMS_TOPK_TEST: 250
    POST_NMS_TOPK_TRAIN: 250
    POST_NMS_TOPK_TEST: 250
  TRIDENT:
    NUM_BRANCH: 3
    BRANCH_DILATIONS: [1, 2, 3]
    TEST_BRANCH_IDX: 1
    TRIDENT_STAGE: "res4"
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
  DIGIT_ONLY: True
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (40000,)
  MAX_ITER: 50000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000
INPUT:
  CROP:
    ENABLED: False
    SIZE: [ 0.8, 1.0 ]
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640)
  MAX_SIZE_TEST: 800
  MIN_SIZE_TEST: 480
SEED: 0
VERSION: 2
