_BASE_: "Base-TridentNet-Fast-C4.yaml"
MODEL:
  WEIGHTS: "model_final_756cda.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
  DIGIT_ONLY: True
  TRAIN_VIDEO_IDS: [0,1,3]
  TEST_VIDEO_IDS: [2]
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.01 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (20000, 40000)
  MAX_ITER: 50000
  WARMUP_FACTOR: 0.0005
  WARMUP_ITERS: 2000
DATALOADER:
  NUM_WORKERS: 3
OUTPUT_DIR: ./output/trident_net/test_video_2