_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  ROI_HEADS:
    NAME: PGMaskingROIHeads
    PROPOSAL_APPEND_GT: True
    ENABLE_POSE_GUIDE: True
  ROI_NUMBER_BOX_HEAD:
    NUM_CONV: 0
    NUM_FC: 0
  ROI_JERSEY_NUMBER_NECK:
    NAME: None
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/pred_number/test_0_gn_digit_number_per_ins