_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  WEIGHTS: "output/pg_rcnn/aug/datasets_mix/pretrain_coco_svhn_3x/model_final.pth"
  ROI_HEADS:
    NAME: PGROIHeads
    PROPOSAL_APPEND_GT: True
    ENABLE_POSE_GUIDE: True
  ROI_DIGIT_NECK:
    NAME: "" # DigitNeck
  ROI_NUMBER_BOX_HEAD:
    NUM_CONV: 0
    NUM_FC: 2
    POOLER_RESOLUTION: (7, 7)
    SEQUENCE_RESOLUTION: (1, 7)
  ROI_NUMBER_NECK:
    NAME: "NumberNeck"
  ROI_NUMBER_NECK_OUTPUT:
    ADD_BOX_CONSTRAINTS: True
INPUT:
  AUG:
    COPY_PASTE_MIX: 5
    HELPER_DATASET_NAME: svhn_train
SOLVER:
  MAX_ITER: 100000
  STEPS: (80000,)
  BASE_LR: 0.0004
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/pred_number/test_0_gn_number_per_box_swapdigit_constraints_copypastemix_pretrain_3x