_BASE_: "../../pg_rcnn_base.yaml"
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
INPUT:
  CROP:
    ENABLED: True
    SIZE: [ 0.7, 1.0 ]
OUTPUT_DIR: ./output/pg_rcnn/aug/random_crop/test_0