_BASE_: "../../pg_rcnn_base.yaml"
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
INPUT:
  CROP:
    ENABLED: True
    SIZE: [ 0.7, 1.0 ]
SOLVER:
  BASE_LR: 0.0005 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (20000, 40000)
  MAX_ITER: 50000
  WARMUP_FACTOR: 0.0002
  WARMUP_ITERS: 5000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: ./output/pg_rcnn/aug/random_crop/test_0