_BASE_: "../../pg_rcnn_base.yaml"
DATASETS:
  TRAIN_VIDEO_IDS: [0,1,3]
  TEST_VIDEO_IDS: [2]
INPUT:
  MAX_SIZE_TEST: 200
  AUG:
    COPY_PASTE_MIX: 22
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
OUTPUT_DIR: ./output/pg_rcnn/aug/copy_paste_mix/test_2