_BASE_: "../../detectron2/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x/137849621/model_final_a6e10b.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
  DIGIT_ONLY: True
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (40000,)
  MAX_ITER: 50000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: ./output/faster_rcnn/test_video_0/
INPUT:
  CROP:
    ENABLED: True
    SIZE: [ 0.8, 1.0 ]
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640)
  MAX_SIZE_TEST: 800
  MIN_SIZE_TEST: 480
SEED: 0
VIS_PERIOD: 0
VERSION: 2