_BASE_: "faster_rcnn_base.yaml"
INPUT:
  CROP:
    ENABLED: False
    SIZE: [ 0.8, 1.0 ]
  AUG:
    COPY_PASTE_MIX: 22
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/faster_rcnn/test_0_copypastemix
