_BASE_: "pg_rcnn_base.yaml"
MODEL:
  ROI_DIGIT_HEAD:
    NUM_PROPOSAL: 20
DATASETS:
  TRAIN: ("svhn_train",) #("keypoints_coco_2017_val_100", "jerseynumbers_train") #
  TEST: ("keypoints_coco_2017_val_100",)
  NUM_IMAGES: 200 # change the number of images to load
  TRAIN_VIDEO_IDS: [1]
  TEST_VIDEO_IDS: [1]
INPUT:
  MIN_SIZE_TRAIN: (640,)
  MIN_SIZE_TEST: 640
  AUG:
    COPY_PASTE_MIX: 0
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (1500, )
  MAX_ITER: 2000
  WARMUP_FACTOR: 0.002
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 500
DATALOADER:
  SHUFFLE: False
  SAMPLER_TRAIN: WeightedTrainingSampler
  NUM_WORKERS: 2
OUTPUT_DIR: ./output/pg_rcnn/test/