_BASE_: "pg_rcnn_base.yaml"
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01 # when IMS_PER_BATCH = 16, LR is 0.02
#  STEPS: (20000, 40000)
  MAX_ITER: 1000
  WARMUP_FACTOR: 0.0005
  WARMUP_ITERS: 2000
DATALOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: ./output/pg_rcnn/test/