_BASE_: "pg_rcnn_base.yaml"
DATASETS:
  NUM_IMAGES: 1 # change the number of images to load
  TRAIN_VIDEO_IDS: [1]
  TEST_VIDEO_IDS: [1]
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
  MIN_SIZE_TRAIN: (640, )
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (600, )
  MAX_ITER: 1000
  WARMUP_FACTOR: 0.005
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 500
DATALOADER:
  NUM_WORKERS: 1
OUTPUT_DIR: ./output/pg_rcnn/test/