_BASE_: "pg_rcnn_base.yaml"
MODEL:
  WEIGHTS: "model_final_a6e10b.pkl" # "./model_final_280758.pkl"
DATASETS:
  TRAIN_VIDEO_IDS: [0,2,3]
  TEST_VIDEO_IDS: [1]
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
SOLVER:
  IMS_PER_BATCH: 8
DATALOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: ./output/pg_rcnn/test_video_1/