_BASE_: "pg_rcnn_base.yaml"
MODEL:
  ROI_DIGIT_HEAD:
    NUM_PROPOSAL: 10
DATASETS:
  NUM_IMAGES: -1 # change the number of images to load
  TRAIN_VIDEO_IDS: [1]
  TEST_VIDEO_IDS: [1]
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
  MIN_SIZE_TRAIN: (640, )
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (15000, )
  MAX_ITER: 20000
  WARMUP_FACTOR: 0.0005
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: ./output/pg_rcnn/test_single_video/