_BASE_: "../../detectron2/configs/COCO-Keypoints/keypoint_rcnn_X_101_32x8d_FPN_3x.yaml"
MODEL:
  DEVICE: cuda # cpu or cuda
  WEIGHTS: "detectron2://COCO-Keypoints/keypoint_rcnn_X_101_32x8d_FPN_3x/139686956/model_final_5ad38f.pkl"
  META_ARCHITECTURE: "PGRCNN"
  KEYPOINT_ON: True
  ROI_HEADS:
    NAME: PGROIHeads
    NUM_CLASSES: 1
  ROI_KEYPOINT_HEAD:
    NAME: KPGRCNNHead
    NUM_KEYPOINTS: 17
  ROI_DIGIT_NECK:
    NAME: DigitNeck
  ROI_NECK_BASE_BRANCHES:
    NORM: "GN"
    PERSON_BRANCH:
      NAME: "PersonROIBranch"
      UP_SCALE: 1
      DECONV_KERNEL: 4
    KEYPOINTS_BRANCH:
      NAME: "KptsROIBranch" # "KptsROIBranch"
      DECONV_KERNEL: 4
      UP_SCALE: 1
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
  DIGIT_ONLY: False
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
  NUM_IMAGES: -1 # change the number of images to load
INPUT:
  CROP:
    ENABLED: False
    SIZE: [ 0.8, 1.0 ]
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640)
  MAX_SIZE_TEST: 800
  MIN_SIZE_TEST: 480
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (40000,)
  MAX_ITER: 50000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 4
TEST:
  # we only evaluate the annotation of 4 keypoints
  KEYPOINT_OKS_SIGMAS: [0.079, 0.079, 0.107, 0.107]
OUTPUT_DIR: ./output/pg_rcnn/model_size/X101-FPN_test_0_gn
SEED: 0
VIS_PERIOD: 0
VERSION: 2