_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  WEIGHTS: "output/pg_rcnn/aug/datasets_mix/pretrain_coco_svhn_3x/model_final.pth"
  ROI_DIGIT_NECK:
    NORM: "GN"
  ROI_DIGIT_NECK_BRANCHES:
    NORM: "GN"
#  ROI_HEADS:
#    OFFSET_TEST: 0.1
INPUT:
  AUG:
    COPY_PASTE_MIX: 22
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (240000,)
  MAX_ITER: 300000
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_gn_pretrain_copypastemix_3x