_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  WEIGHTS: "output/pg_rcnn/aug/datasets_mix/pretrain_coco_svhn_3x/model_final.pth"
  ROI_JERSEY_NUMBER_DET:
    NAME: "SequenceModel"
    NUMBER_POOLER_RESOLUTION: (1, 7)
    SEQUENCE_RESOLUTION: (1, 7)
  ROI_JERSEY_NUMBER_NECK:
    NAME: "NumberNeck"
#    NAME: None
  ROI_NECK_BASE:
    USE_PERSON_BOX_FEATURES: True
    USE_KEYPOINTS_FEATURES: True
    FUSION_TYPE: "cat" # cat sum multiply
    NORM: "GN"
    NUM_PROPOSAL_TRAIN: 100
  ROI_NECK_OUTPUT:
    NORM: "GN"
  ROI_DIGIT_NECK:
    NAME: ""
  ROI_NECK_BASE_BRANCHES:
    NORM: "GN"
    PERSON_BRANCH:
      NAME: "PersonROIBranch"
      UP_SCALE: 1
      DECONV_KERNEL: 4
    KEYPOINTS_BRANCH:
      NAME: "KptsROIBranch" # "KptsROIBranch"
      DECONV_KERNEL: 4
      UP_SCALE: 1
INPUT:
  AUG:
    COPY_PASTE_MIX: 22
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_gn_seq_only_pretrain_copypastemix