_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  ROI_DIGIT_NECK:
    USE_PERSON_BOX_FEATURES: False
    USE_KEYPOINTS_FEATURES: True
    FUSION_TYPE: "" # "cat"
  ROI_DIGIT_NECK_BRANCHES:
    NORM: ""
    PERSON_BRANCH:
      NAME: ""
    KEYPOINTS_BRANCH:
      NAME: "KptsROIBranch"
      UP_SCALE: 2
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_kptsfeatureonly