_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  ROI_DIGIT_NECK:
    NORM: "GN"
  ROI_DIGIT_NECK_BRANCHES:
    NORM: "GN"
INPUT:
  CROP:
    ENABLED: True
    SIZE: [ 0.7, 1.0 ]
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_gn_randcrop