_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  ROI_DIGIT_NECK:
    NORM: "GN"
  ROI_DIGIT_NECK_BRANCHES:
    NORM: "GN"
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
INPUT:
  AUG:
    COPY_PASTE_MIX: 0
    RANDCOLOR: True
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_gn_randcolor