_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  ROI_DIGIT_NECK:
    FUSION_TYPE: "sum"
    NORM: ""
  ROI_DIGIT_NECK_BRANCHES:
    NORM: "GN"
    KEYPOINTS_BRANCH:
      NAME: "KptsAttentionBranch"
      UP_SCALE: 2
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/test_0_attn