_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  ROI_NECK_BASE:
    NORM: "GN"
  ROI_NECK_BASE_BRANCHES:
    NORM: "GN"
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_gn