_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  ROI_DIGIT_NECK:
    NORM: "BN"
  ROI_DIGIT_NECK_BRANCHES:
    NORM: "BN"
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_bn