_BASE_: "../pg_rcnn_base.yaml"
INPUT:
  CROP:
    ENABLED: True
    SIZE: [ 0.7, 1.0 ]
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
OUTPUT_DIR: ./output/pg_rcnn/ablations/test_0_randcrop