_BASE_: "../../pg_rcnn_base.yaml"
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TRAIN_VIDEO_IDS: [0,1,3]
  TEST_VIDEO_IDS: [2]
MODEL:
  WEIGHTS: "output/pg_rcnn/aug/datasets_mix/pretrain_coco_svhn_3x/model_final.pth"
INPUT:
  MAX_SIZE_TEST: 320
  AUG:
    COPY_PASTE_MIX: 22
DATALOADER:
  SAMPLER_TRAIN: WeightedTrainingSampler
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (80000,)
  MAX_ITER: 100000
OUTPUT_DIR: ./output/pg_rcnn/aug/datasets_mix/pretrain_test_2