_BASE_: "../../pg_rcnn_base.yaml"
DATASETS:
  TRAIN: ("svhn_train", "keypoints_coco_2017_train")
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
INPUT:
#  MAX_SIZE_TEST: 320
  AUG:
    COPY_PASTE_MIX: 22
DATALOADER:
  SAMPLER_TRAIN: WeightedTrainingSampler
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (120000,)
  MAX_ITER: 150000
OUTPUT_DIR: ./output/pg_rcnn/aug/datasets_mix/pretrain_coco_svhn_3x