_BASE_: "../../pg_rcnn_base.yaml"
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TRAIN_VIDEO_IDS: [0,1,2]
  TEST_VIDEO_IDS: [3]
MODEL:
  WEIGHTS: "output/pg_rcnn/aug/datasets_mix/pretrain_coco_svhn_3x/model_final.pth"
INPUT:
  MAX_SIZE_TEST: 512
  AUG:
    COPY_PASTE_MIX: 22
DATALOADER:
  SAMPLER_TRAIN: WeightedTrainingSampler
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0002 # when IMS_PER_BATCH = 16, LR is 0.02
#  STEPS: ()
#  MAX_ITER: 40000
OUTPUT_DIR: ./output/pg_rcnn/aug/datasets_mix/pretrain_test_3