_BASE_: "../R101-FPN_pg_rcnn_base.yaml"
MODEL:
  ROI_HEADS:
    NAME: PGROIHeads
    PROPOSAL_APPEND_GT: True
    ENABLE_POSE_GUIDE: True
  ROI_DIGIT_BOX_HEAD:
    POOLER_RESOLUTION: 14
  ROI_DIGIT_NECK_OUTPUT:
    OUTPUT_HEAD_CHANNELS: (2, 2, 2)
    CONV_DIM: 256
    NUM_DIGITS_CLASSIFIER_ON: False
  ROI_NECK_BASE_BRANCHES:
    NORM: "GN"
    PERSON_BRANCH:
      NAME: "PersonROIBranch"
      UP_SCALE: 2
      DECONV_KERNEL: 4
    KEYPOINTS_BRANCH:
      NAME: "KptsROIBranch" # "KptsROIBranch"
      DECONV_KERNEL: 4
      UP_SCALE: 2
  ROI_NECK_BASE:
    BATCH_DIGIT_SIZE_PER_IMAGE: 128
    NUM_PROPOSAL_TRAIN: 25
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
#INPUT:
#  AUG:
#    HELPER_DATASET_NAME: svhn_train
#    COPY_PASTE_MIX: 5
OUTPUT_DIR: ./output/pg_rcnn/model_size/R101-FPN_test_0_gn_bigger
