_BASE_: "../R101-FPN_pg_rcnn_base.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 0
  RPN:
    PRE_NMS_TOPK_TRAIN: 128  # Per FPN level
    POST_NMS_TOPK_TRAIN: 64
  ROI_HEADS:
    PROPOSAL_APPEND_GT: False
    ENABLE_POSE_GUIDE: False
  ROI_DIGIT_BOX_HEAD:
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("svhn_train", "keypoints_coco_2017_train")
INPUT:
#  MAX_SIZE_TEST: 320
  AUG:
    COPY_PASTE_MIX: 5
    RANDCOLOR: True
DATALOADER:
  SAMPLER_TRAIN: WeightedTrainingSampler
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (60000,)
  MAX_ITER: 75000
OUTPUT_DIR: ./output/pg_rcnn/model_size/R101-FPN_pretrain_coco_svhn_3x