_BASE_: "../pg_rcnn_base.yaml"
MODEL:
  WEIGHTS: "output/pg_rcnn/aug/datasets_mix/pretrain_coco_svhn_3x/model_final.pth"
  ROI_HEADS:
    NAME: PGROIHeads
    PROPOSAL_APPEND_GT: True
    ENABLE_POSE_GUIDE: True
  ROI_NUMBER_BOX_HEAD:
    NUM_CONV: 0
    NUM_FC: 0
    POOLER_RESOLUTION: (7, 7)
  ROI_NUMBER_NECK:
    NAME: ""
  ROI_DIGIT_NECK_OUTPUT:
    OUTPUT_HEAD_CHANNELS: (2, 2, 2)
    NUM_DIGITS_CLASSIFIER_ON: True
    ADD_BOX_CONSTRAINTS: True
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
INPUT:
  AUG:
    COPY_PASTE_MIX: 5
    HELPER_DATASET_NAME: svhn_train
OUTPUT_DIR: ./output/pg_rcnn/digit_twochannels/test_0_gn_pretrain_copypastemix_swapdigit_constraint
